# Generated by Django 5.0.1 on 2025-03-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191, null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('Birth_date', models.DateField(null=True)),
                ('contact', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=191, null=True, unique=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('sslc_per', models.CharField(max_length=100, null=True)),
                ('passout_year_sslc', models.CharField(max_length=4, null=True)),
                ('hsc_per', models.CharField(max_length=100, null=True)),
                ('passout_year_hsc', models.CharField(max_length=4, null=True)),
                ('skill', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Docs/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='Docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
                ('position', models.CharField(max_length=191)),
                ('previous_status', models.CharField(blank=True, max_length=191, null=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('linkedin', models.URLField()),
                ('branch', models.CharField(max_length=100)),
                ('passout_year', models.CharField(max_length=4)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Docs/')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(max_length=191)),
                ('skill', models.CharField(max_length=191)),
                ('date_of_drive', models.DateField()),
                ('backlogs', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('passout_year', models.CharField(max_length=4, null=True)),
                ('backlogs', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('placement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
        ),
    ]
